##################################################################################################
# Template for register service with ISTIO under base_url (e.g. https://istiosvc.sdt.blue.watson-health.ibm.com)
# author: Bo Yang, yangbbo@cn.ibm.com 
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: PROJECT-NAME
spec:
  hosts:
  - "*"
  gateways:
  - nodeapp-gateway.sdt-whct-istio1-workspace-ns.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /SERVICE-STAGENAME/
    rewrite:
      uri: /
    route:
    - destination:
        host: SERVICE-NAME-IN-NAMESPACE.NAMESPACE.svc.cluster.local
        port:
          number: SERVICE-PORT
